service: test-bump-lambda-sandbox

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  profile: sandbox
  environment:
    APP_PRIVATE_KEY: ${env:APP_PRIVATE_KEY}
    APP_ID: ${env:APP_ID}
    APP_INSTALLATION_ID: ${env:APP_INSTALLATION_ID}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
          Resource: !GetAtt DependenciesTable.Arn

functions:
  packageBumper:
    handler: dist/index.handler
    environment:
      DYNAMODB_TABLE: !Ref DependenciesTable
      GIT_OWNER: "seccl-platform-test"
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    DependenciesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Dependencies
        AttributeDefinitions:
          - AttributeName: package_name
            AttributeType: S
        KeySchema:
          - AttributeName: package_name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  patterns:
    - "!**"
    - dist/**
    - node_modules/**
    - package.json
  excludeDevDependencies: true
