service: test-bump-lambda-sandbox

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: sandbox
  environment:
    APP_PRIVATE_KEY: ${env:APP_PRIVATE_KEY}
    APP_ID: ${env:APP_ID}
    APP_INSTALLATION_ID: ${env:APP_INSTALLATION_ID}

plugins:
  - serverless-better-credentials
  - serverless-plugin-typescript

functions:
  myLambda:
    handler: dist/index.handler
    events:
      - http:
          path: hello
          method: get
